DEBUG = False
PORT = 8080
PROPAGATE_EXCEPTIONS = True
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = "postgres://cenfjtsz:qzLJvx4G7HSEfBSRH_Y_-L6ENzvD8UGg@salt.db.elephantsql.com:5432/cenfjtsz"
SQLALCHEMY_POOL_SIZE = 10
